{
"spider":"./jar/f1002.jar",
"logo":"./馬年.gif",
"lives":[
{"name":"立視LiTV_php🇹🇼","url": "./py/litv_ts.php","ext": {},"epg": "https://cdn.1678520.xyz/epg/?ch={name}&date={date}","logo":"https://epg.112114.xyz/logo/{name}.png"},
{"name":"4gTV🇹🇼","type": 3,"api": "./py/台湾4g备用.py","ext": {},"epg": "https://cdn.1678520.xyz/epg/?ch={name}&date={date}","logo":"https://epg.112114.xyz/logo/{name}.png"},
{"name":"只有CCTV3🇨🇳","url":"./tvbus/liveCCTV3A.txt","ua":"okhttp/3.15","epg":"https://cdn.1678520.xyz/epg/?ch={name}&date={date}","logo":"https://epg.112114.xyz/logo/{name}.png"},  
{"name":"冰茶🇨🇳","type":0,"url":"https://bc.188766.xyz/?ip=&mishitong=true&mima=mianfeibuhuaqian&json=true","timeout":10,"ua":"bingcha/1.1(mianfeifenxiang)"},
{"name":"大陸1️⃣🇨🇳","url":"https://raw.githubusercontent.com/10000ge10000/iptv-api/refs/heads/master/output/user_result.m3u","ua":"okhttp/3.15","epg":"https://cdn.1678520.xyz/epg/?ch={name}&date={date}","logo":"https://epg.112114.xyz/logo/{name}.png"},  
{"name":"大陸2️⃣多源🇨🇳耐心轉圓圈","url":"https://raw.githubusercontent.com/Guovin/iptv-api/gd/output/result.m3u","ua":"okhttp/3.15","epg":"https://cdn.1678520.xyz/epg/?ch={name}&date={date}","logo":"https://epg.112114.xyz/logo/{name}.png"},  
{"name":"范明明（需开启V6网络）","type":0,"url":"https://nos.netease.com/ysf/3d75a78a0fc7ede372c03598d6d10367.m3u","playerType":2},
{"name":"YouTube🇹🇼","type":0,"url":"./tvbus/YouTube(1).txt","ua":"okhttp/3.15","epg":"https://cdn.1678520.xyz/epg/?ch={name}&date={date}","logo":"https://epg.112114.xyz/logo/{name}.png"},    
{"name":"AnboxII🇹🇼🇨🇳","url":"http://firebase.anbox118.workers.dev/","ua":"okhttp/3.15","epg":"https://cdn.1678520.xyz/epg/?ch={name}&date={date}","logo":"https://epg.112114.xyz/logo/{name}.png"},  
{"name":"大陸✅ 🇨🇳","type": 3,"api": "./py/live_zxbv.py","ext": {},"epg": "https://cdn.1678520.xyz/epg/?ch={name}&date={date}","logo":"https://epg.112114.xyz/logo/{name}.png"},
{"name":"立視LiTV_py🇹🇼","type":3,"api":"./py/live_litv.py","ext":{},"epg":"https://cdn.1678520.xyz/epg/?ch={name}&date={date}","logo":"https://epg.112114.xyz/logo/{name}.png"},
{"name":"四季線上4gtv🇹🇼","url":"./tvbus/4gtv直播源.txt","ua":"okhttp/3.15","epg":"https://cdn.1678520.xyz/epg/?ch={name}&date={date}","logo":"https://epg.112114.xyz/logo/{name}.png"},
{"name":"SMT(有大陸)🇹🇼🇨🇳","type":3,"url":"https://raw.githubusercontent.com/doube-ba/TVlogo/refs/heads/main/smt.txt","api":"./py/SMT.py","ext":{}},
{"name":"猫佬斯玛特🇹🇼🇨🇳","url":"https://live.catvod.com/tv.m3u"},  
{"name":"猫佬卫视🇨🇳","url":"http://iptv.catvod.com/tv.m3u"},  
{"name":"live🇹🇼","url":"./直播源/live.txt","ua":"okhttp/3.15","epg":"https://cdn.1678520.xyz/epg/?ch={name}&date={date}","logo":"https://epg.112114.xyz/logo/{name}.png"},  
{"name":"live2","url":"./tvbus/live.txt","ua":"okhttp/3.15","epg":"https://cdn.1678520.xyz/epg/?ch={name}&date={date}","logo":"https://epg.112114.xyz/logo/{name}.png"},  
{"name":"💿只有音樂","url":"./tvbus/music.txt","ua":"okhttp/3.15","epg":"https://cdn.1678520.xyz/epg/?ch={name}&date={date}","logo":"https://epg.112114.xyz/logo/{name}.png"},  
{"name":"MyTvSuper","url":"http://xg.52sw.top/play/mytvsuper/index-mytvsuper.php","epg":"https://cdn.1678520.xyz/epg/?ch={name}&date={date}","logo":"https://epg.112114.xyz/logo/{name}.png"}

],
"hosts":["cache.ott.*.itv.cmvideo.cn=itv.dns.52top.com.cn"],
"sites":[
{"key":"drpy","name":"2026👉馬上封猴💥馬到發財🤗馬到成功🦓龍馬精神🌋馬年大吉♐馬到平安","type":3, "api":"csp_DouDouGuard","indexs":1,"searchable":1,"quickSearch":1,"changeable":1},
{"key":"sq豆瓣","name":"2026👉馬上封猴💥馬到發財🤗馬到成功🦓龍馬精神🌋馬年大吉♐馬到平安","type":3,"api":"./lib/drpy.min.sq.js","ext":"./js/豆瓣.js"},
{"key":"py_py_douban","name":"2026👉馬上封猴💥馬到發財🤗馬到成功🦓龍馬精神🌋馬年大吉♐馬到平安","type":3,"api":"./py/py_douban.py","searchable":1,"quickSearch":1,"filterable":1,"changeable":1},
{"key":"新韩剧网","name":"新韓劇網.py","type":3,"api":"./py/新韩剧网.min.py","searchable":1,"quickSearch":0,"filterable":0,"changeable":0,"ext":{}},
{"key":"ikanbotsq","name":"🈵爱看机器人sq","type":3,"api":"./lib/drpy.min.sq.js","ext":"./js/ikanbotsq.js","searchable":1,"changeable":1},
{"key":"瓜子短劇","name":"✅瓜子短劇","type":3,"api":"csp_Gz360","searchable":1,"quickSearch":1,"filterable":1,"order_num":0,"jar":"./jar/nzk.jar","changeable":1},
{"key":"太硬白白","name":"✅白白(高清)","type":3,"api":"csp_SbaibaiGuard","timeout":15,"playerType":2,"searchable":1,"quickSearch":1,"changeable":1},
{"key":"太硬南瓜","name":"✅南瓜","type":3,"api":"csp_NanGuaGuard","timeout":15,"playerType":2,"searchable":1,"quickSearch":1,"changeable":1},
{"key":"太硬苹果","name":"✅苹果(高清)","type":3,"api":"csp_LiteAppleGuard","timeout":15,"searchable":1,"quickSearch":1,"changeable":1},
{"key":"太硬文采","name":"✅文采(高清)","type":3,"api":"csp_JpysGuard","timeout":15,"playerType":2,"searchable":1,"quickSearch":1,"changeable":1},
{"key":"太硬比特","name":"✅比特(高清)","type":3,"api":"csp_BttwooGuard","timeout":15,"searchable":1,"quickSearch":1,"changeable":1},
{"key":"太硬厂长","name":"✅廠長(高清)","type":3,"api":"csp_NewCzGuard","timeout":15,"playerType":2,"searchable":1,"quickSearch":1,"changeable":1},
{"key":"Apple.py","name":"蘋果.py","type":3,"api":"./py/Apple.py","searchable":1,"quickSearch":1,"filterable":1,"changeable":1},
{"key":"py_nivod_cc.py","name":"泥視頻.py","type":3,"api":"./py/py_nivod_cc.py","searchable":1,"quickSearch":1,"filterable":1,"changeable":1},
{"key": "py_64832281816dd9a7b7c506233d457a5d","name": "🍎官方采集(T4)","type": 4,"api": "https://py.doube.eu.org/v2/spider?site=64832281816dd9a7b7c506233d457a5d","searchable": 1,"quickSearch": 0,"filterable": 0,"changeable": 0},
{"key": "py_9037cfae7c64405111e0e364401adb60","name": "🍎小苹果(T4)","type": 4,"api": "https://py.doube.eu.org/v2/spider?site=9037cfae7c64405111e0e364401adb60","searchable": 1,"quickSearch": 0,"filterable": 0,"changeable": 0},
{"key": "py_OleVod","name": "🍉欧乐影院(T4)","type": 4,"api": "https://py.doube.eu.org/spider?site=OleVod","searchable": 1,"quickSearch": 0,"filterable": 0,"changeable": 0},
{"key": "py_Dm84","name": "🍋动漫巴士(T4)","type": 4,"api": "https://py.doube.eu.org/spider?site=Dm84","searchable": 1,"quickSearch": 0,"filterable": 0,"changeable": 0},
{"key":"py_xiaoji.py","name":"小鴨暴走.py","type":3,"api":"./py/py_xiaoji.py","searchable":1,"quickSearch":1,"filterable":1,"changeable":1},
{"key":"小红影视.min.py","name":"小紅追劇.py","type":3,"api":"./py/小红影视.min.py","searchable":1,"quickSearch":0,"filterable":0,"changeable":0,"ext":{}},
{"key":"cctv.py","name":"大陸央視.py","type":3,"api":"./py/cctv.py","searchable":1,"quickSearch":1,"filterable":1,"changeable":1},
{"key":"py_永乐视频 (1)","name":"👑永乐视频HD","type":3,"api":"./py/永乐视频 (1).py","searchable":1,"quickSearch":1,"filterable":1,"changeable":1},
{"key":"py_猎手影视 (1)","name":"🔥猎手影视","type":3,"api":"./py/猎手影视 (1).py","searchable":1,"quickSearch":1,"filterable":1,"changeable":1},
{"key":"py_甜圈短劇","name":"甜圈短劇","type":3,"api":"./py/甜圈短劇.py","searchable":1,"quickSearch":1,"filterable":1,"changeable":1},
{"key":"星芽短劇.py","name":"星芽短劇.py","type":3,"api":"./py/星芽短劇.py","searchable":1,"quickSearch":1,"filterable":1,"changeable":1},
{"key":"聚合短劇真心包","name":"聚合短劇","type":3,"api":"csp_JuheShortDrama","searchable":1,"filterable":0,"switchable":0,"jar":"./jar/custom_spider.jar;md5;43989964965deab2a4b6b48251043412","ext":{"host":{"百度":"https://api.jkyai.top","甜圈":"https://mov.cenguigui.cn","锦鲤":"https://api.jinlidj.com","番茄":"https://reading.snssdk.com","番茄2":"https://fqgo.52dns.cc","星芽":"https://app.whjzjx.cn","星芽登录":"https://u.shytkjgs.com","西饭":"https://xifan-api-cn.youlishipin.com","七猫":"https://api-store.qmplaylet.com","七猫详情":"https://api-read.qmplaylet.com","围观":"https://api.drama.9ddm.com","碎片":"https://free-api.bighotwind.cc","碎片图片":"https://speed.hiknz.com"},"commonConfig":"./js/peizhi.json"}},
{"key":"py_爱瓜影视","name":"🔥爱瓜影视","type":3,"api":"./py/爱瓜影视.py","searchable":1,"quickSearch":1,"filterable":1,"changeable":1},
{"key":"py_賎片","name":"賎片","type":3,"api":"./py/賎片.py","searchable":1,"quickSearch":1,"filterable":1,"changeable":1},
{"key":"py_redflix","name":"redflix","type":3,"api":"./py/redflix.py","searchable":1,"quickSearch":1,"filterable":1,"changeable":1},
{"key":"csp_Bili短劇","name":"B站短劇_s","api":"csp_Bili","type":3,"searchable":1,"quickSearch":1,"filterable":1,"jar":"./jar/XYQH.jar","ext":"./js/Bili短劇.json"},
{"key":"非凡资源_sapper","name":"非凡资源_sa","type":1,"api":"http://ffzy5.tv/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"卧龙资源_sapper","name":"卧龙资源_sa","type":1,"api":"https://wolongzyw.com/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"最大资源_sapper","name":"最大资源_sa","type":1,"api":"https://api.zuidapi.com/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"百度云资源_sapper","name":"百度云资源_sa","type":1,"api":"https://api.apibdzy.com/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"暴风资源_sapper","name":"暴风资源_sa","type":1,"api":"https://bfzyapi.com/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"极速资源_sapper","name":"极速资源_sa","type":1,"api":"https://jszyapi.com/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"天涯资源_sapper","name":"天涯资源_sa","type":1,"api":"https://tyyszy.com/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"无尽资源_sapper","name":"无尽资源_sa","type":1,"api":"https://api.wujinapi.com/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"魔都资源_sapper","name":"魔都资源_sa","type":1,"api":"https://www.mdzyapi.com/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"360资源_sapper","name":"360资源_sa","type":1,"api":"https://360zy.com/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"电影天堂_sapper","name":"电影天堂_sa","type":1,"api":"http://caiji.dyttzyapi.com/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"如意资源_sapper","name":"如意资源_sa","type":1,"api":"https://cj.rycjapi.com/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"旺旺资源_sapper","name":"旺旺资源_sa","type":1,"api":"https://wwzy.tv/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"红牛资源_sapper","name":"红牛资源_sa","type":1,"api":"https://www.hongniuzy2.com/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"光速资源_sapper","name":"光速资源_sa","type":1,"api":"https://api.guangsuapi.com/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"iKun资源_sapper","name":"iKun资源_sa","type":1,"api":"https://ikunzyapi.com/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"优酷资源_sapper","name":"优酷资源_sa","type":1,"api":"https://api.ukuapi.com/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"虎牙资源_sapper","name":"虎牙资源_sa","type":1,"api":"https://www.huyaapi.com/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"新浪资源_sapper","name":"新浪资源_sa","type":1,"api":"http://api.xinlangapi.com/xinlangapi.php/provide/vod","searchable":1,"changeable":1},
{"key":"乐子资源_sapper","name":"乐子资源_sa","type":1,"api":"https://cj.lziapi.com/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"海豚资源_sapper","name":"海豚资源_sa","type":1,"api":"https://hhzyapi.com/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"鲸鱼资源_sapper","name":"鲸鱼资源_sa","type":1,"api":"https://jyzyapi.com/provide/vod","searchable":1,"changeable":1},
{"key":"爱蛋资源_sapper","name":"爱蛋资源_sa","type":1,"api":"https://lovedan.net/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"魔都影视_sapper","name":"魔都影视_sa","type":1,"api":"https://www.moduzy.com/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"非凡API_sapper","name":"非凡API_sa","type":1,"api":"https://api.ffzyapi.com/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"非凡采集_sapper","name":"非凡采集_sa","type":1,"api":"http://cj.ffzyapi.com/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"非凡采集HTTPS_sapper","name":"非凡采集HTTPS_sa","type":1,"api":"https://cj.ffzyapi.com/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"非凡线路1_sapper","name":"非凡线路1_sa","type":1,"api":"http://ffzy1.tv/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"卧龙采集_sapper","name":"卧龙采集_sa","type":1,"api":"https://collect.wolongzyw.com/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"暴风APP_sapper","name":"暴风APP_sa","type":1,"api":"https://app.bfzyapi.com/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"无尽ME_sapper","name":"无尽ME_sa","type":1,"api":"https://api.wujinapi.me/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"天涯海角_sapper","name":"天涯海角_sa","type":1,"api":"https://tyyszyapi.com/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"光速HTTP_sapper","name":"光速HTTP_sa","type":1,"api":"http://api.guangsuapi.com/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"新浪HTTPS_sapper","name":"新浪HTTPS_sa","type":1,"api":"https://api.xinlangapi.com/xinlangapi.php/provide/vod","searchable":1,"changeable":1},
{"key":"1080JSON_sapper","name":"1080JSON_sa","type":1,"api":"https://api.1080zyku.com/inc/apijson.php","searchable":1,"changeable":1},
{"key":"乐子HTTP_sapper","name":"乐子HTTP_sa","type":1,"api":"http://cj.lziapi.com/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"U酷资源88_sapper","name":"U酷资源88_sa","type":1,"api":"https://api.ukuapi88.com/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"丫丫点播_sapper","name":"丫丫点播_sa","type":1,"api":"https://cj.yayazy.net/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"卧龙CC_sapper","name":"卧龙CC_sa","type":1,"api":"https://collect.wolongzy.cc/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"旺旺API_sapper","name":"旺旺API_sa","type":1,"api":"https://api.wwzy.tv/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"最大点播_sapper","name":"最大点播_sa","type":1,"api":"http://zuidazy.me/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"牛牛点播_sapper","name":"牛牛点播_sa","type":1,"api":"https://api.niuniuzy.me/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"索尼资源_sapper","name":"索尼资源_sa","type":1,"api":"https://suoniapi.com/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"茅台资源_sapper","name":"茅台资源_sa","type":1,"api":"https://caiji.maotaizy.cc/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"豆瓣资源_sapper","name":"豆瓣资源_sa","type":1,"api":"https://dbzy.tv/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"速博资源_sapper","name":"速博资源_sa","type":1,"api":"https://subocaiji.com/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"金鹰点播_sapper","name":"金鹰点播_sa","type":1,"api":"https://jinyingzy.com/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"閃電资源_sapper","name":"閃電资源_sa","type":1,"api":"https://sdzyapi.com/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"飘零资源_sapper","name":"飘零资源_sa","type":1,"api":"https://p2100.net/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"魔都动漫_sapper","name":"魔都动漫_sa","type":1,"api":"https://caiji.moduapi.cc/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"索尼-闪电_sapper","name":"索尼-闪电_sa","type":1,"api":"https://xsd.sdzyapi.com/api.php/provide/vod","searchable":1,"changeable":1},
{"key":"应用商店","name":"应用商店","type":3,"api":"csp_Market","searchable":1,"changeable":1,"ext":"./js/market.json","style":{"type":"rect","ratio":1}}
],
"parses":[
{"name":"解析聚合","type":3,"url":"Demo"},
{"name":"Json并发","type":2,"url":"Parallel"},
{"name":"Json轮询","type":2,"url":"Sequence"},
{"name":"modujx01","type":0,"url":"https://jiexi.modujx01.com/?url="},
{"name":"777","type":0,"url":"https://jx.777jiexi.com/player/?url="},
{"name":"17号线","type":0,"url":"https://www.yemu.xyz/?url=","ext":{"flag":["qq","腾讯","qiyi","iqiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"看看","type":0,"url":"https://jx.m3u8.pw/?url="},
{"name":"360資源資源","type":0,"url":"https://www.360jiexi.com/player/?url="},
{"name":"暴風資源","type":0,"url":"https://bfzyplayer.com/player/?url="},
{"name":"非凡資源","type":0,"url":"https://bfzyplayer.com/player/?url="},
{"name":"豪華資源","type":0,"url":"https://hhjiexi.com/play/?url="},
{"name":"量子資源","type":0,"url":"https://lziplayer.com/?url="},
{"name":"櫻花資源","type":0,"url":"https://jx.yhzybf.com/player/jx.php?url="},
{"name":"ikun資源","type":0,"url":"https://www.ikdmjx.com/?url="},
{"name":"tv資源","type":0,"url":"https://jx.m3u8.tv/jiexi/?url="},
{"name":"博民資源","type":0,"url":"https://www.bmm3u8.com/?url="},
{"name":"A01","type":0,"url":"http://api.apii.top/?v="},
{"name":"A05","type":0,"url":"http://www.wpsseo.cn/line.php?n=7&url="},
{"name":"超嗅探","type":3,"url":"Web"},
{"name":"西瓜嗅探1","type":0,"url":"https://t1.qlplayer.cyou/player/analysis.php?v=","ext":{"flag":["qq","腾讯","企鹅","IQiYi","qiyi","爱奇艺","奇艺","youku","YouKu","优酷","sohu","SoHu","搜狐","letv","LeShi","乐视","imgo","mgtv","MangGuo","芒果","SLYS4k","BYGA","luanzi","AliS","dxzy","bilibili","QEYSS","xigua","西瓜视频","腾讯视频","奇艺视频","优酷视频","芒果视频","乐视视频"],"header":{"User-Agent":"Dart/3.0(dart:io)"}}},
{"name":"西瓜嗅探2","type":0,"url":"https://t1.qlplayer.cyou/player/?url=","ext":{"flag":["qq","腾讯","企鹅","IQiYi","qiyi","爱奇艺","奇艺","youku","YouKu","优酷","sohu","SoHu","搜狐","letv","LeShi","乐视","imgo","mgtv","MangGuo","芒果","SLYS4k","BYGA","luanzi","AliS","dxzy","bilibili","QEYSS","xigua","西瓜视频","腾讯视频","奇艺视频","优酷视频","芒果视频","乐视视频"],"header":{"User-Agent":"Dart/3.0(dart:io)"}}},{"name":"高清嗅探","type":0,"url":"https://jx.xmflv.com?url=","ext":{"flag":["qq","腾讯","企鹅","IQiYi","qiyi","爱奇艺","奇艺","youku","YouKu","优酷","sohu","SoHu","搜狐","letv","LeShi","乐视","imgo","mgtv","MangGuo","芒果","SLYS4k","BYGA","luanzi","AliS","dxzy","bilibili","QEYSS","xigua","西瓜视频","腾讯视频","奇艺视频","优酷视频","芒果视频","乐视视频"],"header":{"User-Agent":"Dart/3.0(dart:io)"}}},
{"name":"夜幕嗅探","type":0,"url":"https://www.yemu.xyz/?url=","ext":{"flag":["qq","腾讯","企鹅","IQiYi","qiyi","爱奇艺","奇艺","youku","YouKu","优酷","sohu","SoHu","搜狐","letv","LeShi","乐视","imgo","mgtv","MangGuo","芒果","SLYS4k","BYGA","luanzi","AliS","dxzy","bilibili","QEYSS","xigua","西瓜视频","腾讯视频","奇艺视频","优酷视频","芒果视频","乐视视频"],"header":{"User-Agent":"Dart/3.0(dart:io)"}}},
{"name":"爱心笔记本","type":4,"url":"http://119.91.123.253:2345/Api/yun.php?url="},
{"name":"魏晓芳","type":1,"url":"https://svip.renrenmi.cc:2222/api/?key=ogGC18CjsACNo60r3E&url="},
{"name":"奧斯卡資源","type":0,"url":"https://aosikazyplayurl.com/?url="},
{"name":"色色虎資源","type":0,"url":"https://jx.jxsesehuzy.com/?url="},
{"name":"好色資源","type":0,"url":"https://haosezyplayurl.com/?url="},
{"name":"fuqi","type":1,"url":"https://play.fuqizhishi.com/maotv/API.php?appkey=xiongdimenbieguaiwodingbuzhulegailekey07201538&url="},
{"name":"盘古","type":0,"url":"https://www.m3u8.tv.cdn.8old.cn/jx.php?url="},
{"name":"左岸","type":1,"url":"http://110.42.2.115:880/analysis/json/?uid=2100&my=fgjnoqstLMRUZ03489&url=","ext":{"flag":["qq","qiyi","mgtv","youku","letv","sohu","xigua","1905","优播线路","腾播线路"],"header":{"User-Agent":"Dart/2.14(dart:io)"}}},
{"name":"太空","type":1,"url":"http://124.222.68.182/jiexi/4kJX.php/?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","sohu","搜狐","letv","乐视","mgtv","芒果","CL4K","renrenmi","ltnb","bilibili","1905","xigua"]}},
{"name":"未知","type":1,"url":"http://106.52.218.221:88/?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"随便1","type":1,"url":"http://cl.yjhan.com:8090/home/api?type=ys&uid=821518&key=aghlmnyBFIJMPRX489&url="},
{"name":"随便2","type":1,"url":"https://www.nfjx.xyz/home/api?type=ys&uid=5767995&key=ijkmovxDEHIJPQRW69&url="},
{"name":"LTRX","type":1,"url":"https://svip.spchat.top/api/?type=ys&key=bKemW41JnxmQb4l67h&url=","ext":{"flag":["rx"]}},
{"name":"OJBK","type":0,"url":"https://jmwl.qd234.cn/v/?v=","ext":{"flag":["ltnb","renrenmi","rx","xfyun","muxm3u8","xigua","xueren","qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","bilibili","哔哩哔哩","哔哩","pptv","PPTV","sohu","letv"]}},
{"name":"parwix1","type":0,"url":"https://jx.parwix.com:4433/player/?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"parwix2","type":0,"url":"https://jx.parwix.com:4433/player/analysis.php?v=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"线路m9","type":1,"url":"https://api.m3u8.tv:5678/home/api?type=ys&uid=1931000&key=gktuvyzABEORSYZ135&url="},
{"name":"线路NX","type":1,"url":"https://vip.nxflv.com/home/api?uid=701203&key=bltuyCEFKLTX013679&url="},
{"name":"①秒播","type":1,"url":"https://jx.hfyrw.com/mao.go?url="},
{"name":"②秒播","type":1,"url":"http://27.124.4.42:4567/jhjson/ceshi.php?url=","ext":{"flag":["qiyi","qq","letv","sohu","youku","mgtv","bilibili","wasu","xigua","1905"]}},
{"name":"③秒播","url":"http://81.71.48.249:4456/jsonc/293shipin.php?url=","type":1,"i":"77","ext":{"flag":["qiyi","爱奇艺","奇艺","qq","腾讯","youku","优酷","pptv","PPTV","letv","乐视","bilibili","哔哩哔哩","哔哩","mgtv","芒果"]}},
{"name":"④秒播","type":1,"url":"http://106.55.234.91:4433/?url=","ext":{"flag":["qiyi","qq","letv","sohu","youku","mgtv","bilibili","wasu","xigua","1905"]}},
{"name":"⑤秒播","type":1,"url":"http://81.71.48.249:4456/jsonc/longxia.php?url=","ext":{"flag":["qq","qiyi","mgtv","youku","letv","sohu","xigua","1905"],"header":{"User-Agent":"Dart/2.14(dart:io)"}}},
{"name":"⑦秒播","type":1,"url":"https://app.okmedcos.com/4k/?url="},
{"name":"⑧秒播","type":1,"url":"https://jie.1z1.cc/api/?key=HdMmTMfyf1uTOQUL0b&url="},
{"name":"Pro","type":1,"url":"http://api.vip123kan.vip/?url=","ext":{"flag":["youku","优酷","mgtv","芒果","qq","腾讯","qiyi","爱奇艺","qq","奇艺"]}},
{"name":"2","type":1,"url":"https://jx.mczdyw.com/xg.php?url=","ext":{"flag":["mgtv","芒果"]}},
{"name":"3","type":1,"url":"https://www.aiaine.com/api/?key=kVqmG5dAQ5dZTcECw8&url=","ext":{"flag":["youku","优酷","mgtv","芒果","qq","腾讯","qiyi","爱奇艺","qq","奇艺"]}},
{"name":"4","type":1,"url":"https://svip.rongxingvr.top/api/?key=niBgMGXVdCQhsmeEBK&url=","ext":{"flag":["youku","优酷","mgtv","芒果","qq","腾讯","qiyi","爱奇艺","qq","奇艺"]}},
{"name":"8","type":1,"url":"https://app.iminna.com/jx/?url=","ext":{"flag":["youku","优酷","mgtv","芒果","qq","腾讯","qiyi","爱奇艺","qq","奇艺"]}},
{"name":"飓风影院2","type":1,"url":"https://vvip.funsline.cn/api/?key=3xWfEoDf4V9p9Y20CR&url=","ext":{"flag":["ziqie","youku","优酷","qiyi","爱奇艺","奇艺","mgtv","芒果","qq","腾讯"]}},
{"name":"我爱电影网","type":1,"url":"https://jhpc.manduhu.com/j1217.php?url=","ext":{"flag":["qiyi","爱奇艺","奇艺","mgtv","芒果","youku","优酷","pptv","PPTV"]}},
{"name":"王牌","type":1,"url":"https://za.kuanjv.com/?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","搜狐","sohu","letv","乐视","bilibili","哔哩哔哩","哔哩","xigua","西瓜"]}},
{"name":"盘古解析","type":1,"url":"https://json.pangujiexi.com:12345/json.php?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果"]}},
{"name":"杰森","type":0,"url":"https://jx.jsonplayer.com/player/?url="}, 
{"name":"A12","type":0,"url":"https://jx.quankan.app/?url="},
{"name":"A14","type":0,"url":"https://www.pangujiexi.com/pangu/?url="},
{"name":"9号线","url":"https://www.8090g.cn/?url="},
{"name":"12号线","type":0,"url":"https://jx.m3u8.tv/jiexi/?url=","ext":{"flag":["qq","腾讯","qiyi","iqiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"👉嗅探👈就是破解中，請等候一會👈","type":0,"url":"http://pandown.pro/app/ysmjx.php?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"],"header":{"User-Agent":"okhttp/4.1.0"}}}
],
"flags":["youku","qq","iqiyi","qiyi","letv","sohu","tudou","pptv","mgtv","wasu"],
"wallpaper":"./黑色.jpeg",
"rules":[
{"name":"ofiii[台湾节点]","hosts":[    "www.ofiii.com"],"script":[    "const play=document.getElementsByClassName(\"play_icon\")[0];const event=new MouseEvent(\"click\",{bubbles:!0,cancelable:!0,view:window,screenX:100,screenY:100,clientX:50,clientY:50,button:0,shiftKey:!1,ctrlKey:!1,altKey:!1,metaKey:!1,modifierState:0});play.dispatchEvent(event);"]},
{"name":"proxy","hosts":[  "raw.githubusercontent.com",  "googlevideo.com",  "googleapis.com",  "cdn.v82u1l.com",  "cdn.iz8qkg.com",  "cdn.kin6c1.com",  "c.biggggg.com",  "c.olddddd.com",  "haiwaikan.com",  "www.histar.tv",  "youtube.com",  "uhibo.com",  ".*boku.*",  ".*nivod.*",  ".*ulivetv.*"]},
{"name":"火山嗅探","hosts":[  "huoshan.com"],"regex":[  "item_id="]},
{"name":"抖音嗅探","hosts":[  "douyin.com"],"regex":[  "is_play_url="]},
{"name":"农民嗅探","hosts":[  "toutiaovod.com"],"regex":[  "video/tos/cn"]},
{"name":"七新嗅探","hosts":[  "api.52wyb.com"],"regex":[  "m3u8?pt=m3u8"]},
{"name":"毛驴点击","hosts":[  "www.maolvys.com"],"script":[  "document.getElementsByClassName('swal-button swal-button--confirm')[0].click()"]}
],
"ads":["static-mozai.4gtv.tv","s3t3d2y8.afcdn.net"]

}